@startuml suscribirse
actor Colaborador_Usuario as User
participant INTERFAZ
participant CONTROLLER
participant "Colaborador" as Colaborador
participant "Suscripcion" as Suscripcion
participant "GestorDeSuscripciones" as GestorDeSuscripciones
participant Sistema

User -> INTERFAZ: Solicitar suscribirse(heladeraObjetivo, viandasDisponiblesMin, viandasParaLlenarMax, notificarDesperfecto, medioDeContacto)
INTERFAZ -> CONTROLLER: Solicitar suscribirse(heladeraObjetivo, viandasDisponiblesMin, viandasParaLlenarMax, notificarDesperfecto, medioDeContacto)
CONTROLLER -> Colaborador: suscribirse(heladeraObjetivo, viandasDisponiblesMin, viandasParaLlenarMax, notificarDesperfecto, medioDeContacto)
Colaborador -> Suscripcion: darDeAlta()
Suscripcion -> GestorDeSuscripciones: agregarSuscripcion(suscripcion)
GestorDeSuscripciones --> CONTROLLER: Suscripción confirmada
CONTROLLER --> INTERFAZ: Suscripción confirmada
INTERFAZ --> User: Suscripción confirmada
@enduml