@startuml donar_vianda_colaborar
actor Colaborador_Usuario as User
participant INTERFAZ
participant CONTROLLER
participant "Colaborador" as Colaborador
participant "DonacionViandaCreator" as DonacionViandaCreator

User -> INTERFAZ: Solicitar colaborar (DonacionViandaCreator, fechaContribucion, vianda, heladera)
INTERFAZ -> CONTROLLER: Solicitar colaborar (DonacionViandaCreator, fechaContribucion, vianda, heladera)
CONTROLLER -> Colaborador: colaborar(DonacionViandaCreator, fechaContribucion, vianda, heladera)
Colaborador -> Colaborador: esCreatorPermitido(DonacionViandaCreator.getClass())
alt Creator permitido
    Colaborador -> DonacionViandaCreator: crearContribucion(colaborador, fechaContribucion, paraMigrar, vianda, heladera)
    DonacionViandaCreator -> Colaborador: new DonacionVianda(colaborador, fechaContribucion, vianda, heladera)
    Colaborador -> Colaborador: agregarContribucionPendiente(donacionVianda)
    Colaborador --> CONTROLLER: Donación de Vianda creada
    CONTROLLER --> INTERFAZ: Donación de Vianda creada
    INTERFAZ --> User: Donación de Vianda creada
else Creator no permitido
    Colaborador --> CONTROLLER: Error
    CONTROLLER --> INTERFAZ: Error
    INTERFAZ --> User: No es una forma válida de colaborar
end
@enduml