// TODO: Cambiar este Diagrama

@startuml abrir_heladera
actor PersonaEnSituacionVulnerable_Usuario as User
participant INTERFAZ
participant CONTROLLER
participant "PersonaEnSituacionVulnerable" as PersonaEnSituacionVulnerable
participant "TarjetaPersonaEnSituacionVulnerable" as TarjetaPersonaEnSituacionVulnerable
participant "GestorDeAperturas" as GestorDeAperturas
participant "AperturaPersonaEnSituacionVulnerable" as AperturaPersonaEnSituacionVulnerable
participant "Sistema" as Sistema

User -> INTERFAZ: Solicitar adquirirAlimento(heladera)
INTERFAZ -> CONTROLLER: Solicitar adquirirAlimento(heladera)
CONTROLLER -> PersonaEnSituacionVulnerable: adquirirAlimento(heladera)
PersonaEnSituacionVulnerable -> TarjetaPersonaEnSituacionVulnerable: intentarApertura(heladera)
TarjetaPersonaEnSituacionVulnerable -> GestorDeAperturas: revisarPermisoAperturaP(personaEnSituacionVulnerable)
alt Puede usar
    alt Heladera no vacía
        GestorDeAperturas -> TarjetaPersonaEnSituacionVulnerable: Permiso confirmado
        TarjetaPersonaEnSituacionVulnerable -> AperturaPersonaEnSituacionVulnerable: darDeAlta()
        AperturaPersonaEnSituacionVulnerable -> Sistema: agregarAccionHeladera(aperturaPersonaEnSituacionVulnerable)
        Sistema --> AperturaPersonaEnSituacionVulnerable: Apertura registrada
        AperturaPersonaEnSituacionVulnerable --> TarjetaPersonaEnSituacionVulnerable: Apertura registrada
        TarjetaPersonaEnSituacionVulnerable -> TarjetaPersonaEnSituacionVulnerable: agregarUso(uso)
        TarjetaPersonaEnSituacionVulnerable -> CONTROLLER: Apertura registrada
        CONTROLLER --> INTERFAZ: Apertura registrada
        INTERFAZ --> User: Apertura registrada
    else Heladera vacía
        GestorDeAperturas --> TarjetaPersonaEnSituacionVulnerable: Permiso denegado (heladera vacía)
        TarjetaPersonaEnSituacionVulnerable --> CONTROLLER: Permiso denegado (heladera vacía)
        CONTROLLER --> INTERFAZ: Permiso denegado (heladera vacía)
        INTERFAZ --> User: La heladera (nombre) se encuentra vacía
    end
else No puede usar
    GestorDeAperturas --> TarjetaPersonaEnSituacionVulnerable: Permiso denegado (usos agotados)
        TarjetaPersonaEnSituacionVulnerable --> CONTROLLER: Permiso denegado (usos agotados)
        CONTROLLER --> INTERFAZ: Permiso denegado (usos agotados)
        INTERFAZ --> User: Ya agotó los usos diarios de su tarjeta
end
@enduml