@startuml donar_dinero_colaborar
actor Colaborador_Usuario as User
participant INTERFAZ
participant CONTROLLER
participant "Colaborador" as Colaborador
participant "DonacionDineroCreator" as DonarDineroCreator

User -> INTERFAZ: Solicitar colaborar (DonacionDineroCreator, fechaContribucion, monto, frecuencia)
INTERFAZ -> CONTROLLER: Solicitar colaborar (DonacionDineroCreator, fechaContribucion, monto, frecuencia)
CONTROLLER -> Colaborador: colaborar(DonacionDineroCreator, fechaContribucion, monto, frecuencia)
Colaborador -> Colaborador: esCreatorPermitido(DonacionDineroCreator.getClass())
alt Creator permitido
    Colaborador -> DonarDineroCreator: crearContribucion(colaborador, fechaContribucion, monto, frecuencia)
    DonarDineroCreator -> Colaborador: new CargaOferta(colaborador, fechaContribucion, monto, frecuencia)
    Colaborador -> Colaborador: agregarContribucionPendiente(donacionDinero)
    Colaborador --> CONTROLLER: Donación de Dinero creada
    CONTROLLER --> INTERFAZ: Donación de Dinero creada
    INTERFAZ --> User: Donación de Dinero creada
else Creator no permitido
    Colaborador --> CONTROLLER: Error
    CONTROLLER --> INTERFAZ: Error
    INTERFAZ --> User: No es una forma válida de colaborar
end
@enduml