@startuml registrar_persona_en_situacion_vulnerable_confirmar
actor Colaborador_Usuario as User
participant INTERFAZ
participant CONTROLLER
participant "Colaborador" as Colaborador
participant "RegistroDePersonaEnSituacionVulnerable" as RegistroDePersonaEnSituacionVulnerable

User -> INTERFAZ: Solicitar confirmarContribucion(registroDePersonaEnSituacionVulnerable, fechaContribucion)
INTERFAZ -> CONTROLLER: Solicitar confirmarContribucion(registroDePersonaEnSituacionVulnerable, fechaContribucion)
CONTROLLER -> Colaborador: confirmarContribucion(registroDePersonaEnSituacionVulnerable, fechaContribucion)
Colaborador -> RegistroDePersonaEnSituacionVulnerable: confirmar(fechaContribucion)
RegistroDePersonaEnSituacionVulnerable -> RegistroDePersonaEnSituacionVulnerable: marcarComoCompletada()
RegistroDePersonaEnSituacionVulnerable -> RegistroDePersonaEnSituacionVulnerable: calcularPuntos()
RegistroDePersonaEnSituacionVulnerable --> Colaborador: Confirmación válida
Colaborador -> Colaborador: agregarContribucion(registroDePersonaEnSituacionVulnerable)
Colaborador -> Colaborador: eliminarContribucionPendiente(registroDePersonaEnSituacionVulnerable)
Colaborador --> CONTROLLER: Registro de Persona en Situación Vulnerable confirmada
CONTROLLER --> INTERFAZ: Registro de Persona en Situación Vulnerable confirmada
INTERFAZ --> User: Registro de Persona en Situación Vulnerable confirmada
@enduml